# this is workflow name
name: Hello

# runs on a trigger
on:
 push:
   branches: [main]

# these are jobs inside the workflow 
jobs: 

# this is a name of job
greet:
  # this is the github runner
  runs-on: ubuntu-latest
  steps:
   - name: say hello to users
     run: echo "hello dosto" 

   - name: say hello to username
     run: echo "hello $USER"
